### ISSUE TITLE
Need for _notghosttriangles?

### ISSUE THREAD

**Issue by DanielVandH** [COMODO-research/Comodo.jl#31]
Looking at https://github.com/COMODO-research/Comodo.jl/blob/002be3edb6238cde4064dfae2149a2ba9ba443cf/src/functions.jl#L3775-L3795, can't you just pass `delete_ghosts=true` to `triangulate`?

**Comment by Kevin-Mattheus-Moerman** [comment]
@DanielVandH Thanks for checking this out and spotting that. Yes that seems correct. I deleted that unnecessary function just now and used `delete_ghosts=true` as suggested. Thanks!
