### ISSUE TITLE
Use linear interpolation (and other methods) in evenly_sample

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [COMODO-research/Comodo.jl#32]
@jipolanco thanks again for the help on `evenly_sample` in COMODO. I have some questions on the use of BSplineKit. 

Currently the interpolation is hardcoded as: 
```julia
   S = BSplineKit.interpolate(LL, V, BSplineOrder(4), BSplineKit.Natural()) # Create interpolator
```
This means it seems to always feature 4th order natural splines. 
Next the derivative, needed for even sampling, is evaluated as: 
```
dS = Derivative() * S
```
Of course I can change the order/nature of the spline a bit, however, does your package also allow for linear interpolation? 

Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
This is the context at the moment, this video shows curve rounding (actual circular corner segments): 

https://github.com/COMODO-research/Comodo.jl/assets/8392709/175a732c-5a02-4723-ae28-cb31cac7a297

But you can see the point distribution is now "use n-points on the circles" so uneven. It would be better to use n-points on the overall curve, however with the current `evenly_sample` method it looks like we need a linear method when I set the radius to 0 (in this case we only interpolate the black input points which creates the "jump to a spline" artefact): 

https://github.com/COMODO-research/Comodo.jl/assets/8392709/3b743c38-f835-4a29-966d-f1fa38cf1fb1

**Comment by jipolanco** [comment]
I'm not sure I understand the issue, I will try to look at it in more detail later.

For now, just in case it helps, note that setting `BSplineOrder(2)` corresponds to linear interpolation between data points. So you could simply do:

```julia
S = BSplineKit.interpolate(LL, V, BSplineOrder(2)) # Create interpolator
```

Then, if you compute the derivative of `S`, the result is just a piecewise constant function (discontinous at the data points). Is that what you're looking for, or did I misunderstand the problem?

**Comment by Aminofa70** [comment]
Dear Kevin,
Thanks for your great package I can introduce a very robust B-spline and P-spline julia package if you are interested in. I am also developing your code for some projects and keep you posted when it is done. Maybe you will like it. 
Cheers

**Comment by Kevin-Mattheus-Moerman** [comment]
@jipolanco sorry I missed that the order 2 would make it linear, I thought that would make it quadratic. I had set it to 1 an error initially. But thanks, setting the spline order to 2 works. 

I was interpolating a this rounded curve but when the round radius goes to zero it should be a piecewise linear curve. As you can see this works now: 

https://github.com/COMODO-research/Comodo.jl/assets/8392709/cc415c18-98df-4afe-8f23-845447d941ed

**Comment by Kevin-Mattheus-Moerman** [comment]
@Aminofa70 hi, thanks for the comment. Sounds interesting. Looking forward to seeing what you are working on. Currently I use: https://github.com/jipolanco/BSplineKit.jl, and have also used https://juliamath.github.io/Interpolations.jl/latest/, but the former seemed easier to use and I liked that it enabled Natural splines as well as taking derivatives directly. 

If you are working with Comodo that is great. Let me know if you have any suggestions or if you'd like to contribute any new features. We always welcome contributions!
